"""Remove campos modelos, anos e motor da tabela Peca

Revision ID: 0ee0baddd1be
Revises: f01768b556cd
Create Date: 2025-06-08 19:24:57.595439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ee0baddd1be'
down_revision = 'f01768b556cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peca', schema=None) as batch_op:
        batch_op.alter_column('aplicacoes',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.drop_column('motor')
        batch_op.drop_column('anos')
        batch_op.drop_column('modelos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modelos', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('anos', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('motor', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('aplicacoes',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
