"""Add telefone to Pedido

Revision ID: bdd3bbe5d5c9
Revises: 0ee0baddd1be
Create Date: 2025-06-08 20:18:11.929002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd3bbe5d5c9'
down_revision = '0ee0baddd1be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###
