"""Add pagamento_id

Revision ID: cd803d59e1fc
Revises: bdd3bbe5d5c9
Create Date: 2025-06-08 21:23:01.190606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd803d59e1fc'
down_revision = 'bdd3bbe5d5c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pagamento_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('pagamento_id')

    # ### end Alembic commands ###
