"""add campo imagens

Revision ID: f01768b556cd
Revises: 
Create Date: 2025-06-08 06:21:19.311338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f01768b556cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_generico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagens', sa.Text(), nullable=True))

    with op.batch_alter_table('peca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagens', sa.Text(), nullable=True))
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.VARCHAR(length=300), nullable=True))
        batch_op.drop_column('imagens')

    with op.batch_alter_table('item_generico', schema=None) as batch_op:
        batch_op.drop_column('imagens')

    # ### end Alembic commands ###
